// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOebWpSy85zMTMFiSLH1a3RMs7BhBE4u8',
    appId: '1:385851143:web:9545901021c212945aafa2',
    messagingSenderId: '385851143',
    projectId: 'attendace-app-aab1c',
    authDomain: 'attendace-app-aab1c.firebaseapp.com',
    storageBucket: 'attendace-app-aab1c.appspot.com',
    measurementId: 'G-WNMZ6V20ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGkXYHnDXANYQAoE0d81O7kDPiFjjtcKQ',
    appId: '1:385851143:android:869bd89ffb06f71f5aafa2',
    messagingSenderId: '385851143',
    projectId: 'attendace-app-aab1c',
    storageBucket: 'attendace-app-aab1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9YVWplPRAjG8s7zzA-FZ-8-0A__VM17o',
    appId: '1:385851143:ios:dab12c79f9ad14b55aafa2',
    messagingSenderId: '385851143',
    projectId: 'attendace-app-aab1c',
    storageBucket: 'attendace-app-aab1c.appspot.com',
    iosBundleId: 'com.example.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9YVWplPRAjG8s7zzA-FZ-8-0A__VM17o',
    appId: '1:385851143:ios:50d6db75373981c75aafa2',
    messagingSenderId: '385851143',
    projectId: 'attendace-app-aab1c',
    storageBucket: 'attendace-app-aab1c.appspot.com',
    iosBundleId: 'com.example.attendanceapp.RunnerTests',
  );
}
